### ISSUE TITLE
Do I really need X? 

### ISSUE THREAD

**Issue by stahnma** [travisghansen/gentoo-cloud-image-builder#1]
Hey, I haven't time to dig into this much but I did get an error saying I needed X, when I certainly would rather not.

<pre>
[stahnma@dre gentoo-cloud-image-builder]$ ls
builder  config.cfg  config.sh  gentoo.img  iso  isogen.sh  launch.sh  log  metadata  README.md  samples
[stahnma@dre gentoo-cloud-image-builder]$ ./launch.sh -t build
latest iso install-amd64-minimal-20150709.iso already downloaded
latest stage stage3-amd64-20150709.tar.bz2 already downloaded
creating builder iso
creating config iso
char device redirected to /dev/pts/1 (label charserial1)

** (qemu-system-x86_64:491): WARNING **: Could not open X display

(qemu-system-x86_64:491): Gtk-WARNING **: cannot open display:
[stahnma@dre gentoo-cloud-image-builder]$
</pre>

This was running on CentOS 7.

**Comment by travisghansen** [comment]
Hey!  Thanks for trying the project out!  The tool fires up kvm to both install and test the image.  My guess is that with some slight tweaking you could get kvm to fire up with the vnc driver and not need x.  I'll do some research and see if I can get that to work.

In the mean time, I have a couple images I could make available to you if you'd like.

**Comment by travisghansen** [comment]
OK, so I just tested.  If you copy config.cfg.example to config.cfg I've just introduced a new parameter (make sure to pull):
QEMU_EXTRA_OPTS=

QEMU_EXTRA_OPTS="-vnc :0"
Will fire up the vm with the VNC driver which you should then be able to connect on hostip:5900 with the vnc viewer of your choice, alternatively if you want a password on the VNC server it would be:
QEMU_EXTRA_OPTS="-vnc :0,password"

Give it a whirl and let me know how it goes..
